### ISSUE TITLE
Is it runnable? Insert into Repository?

### ISSUE THREAD

**Issue by BackgroundWorkerS** [rgwch/ioBroker.mystrom-wifi-switch#1]

**Comment by rgwch** [comment]
What Repository?

**Comment by GermanBluefox** [comment]
This one,
https://github.com/ioBroker/ioBroker.repositories

So your adapter could be installed via normal admin interface.

**Comment by rgwch** [comment]
Okay, I'll check if I can meet the requirements. By now, it has only the status "works for me" ...

**Comment by GermanBluefox** [comment]
You can announce it in forum. May me some user can test it too. :)

2017-12-19 20:42 GMT+01:00 rgwch <notifications@github.com>:

**Comment by rgwch** [comment]
There is now one Person besides me who uses the adapter (https://github.com/rgwch/ioBroker.mystrom-wifi-switch/issues/3) which happens to be my minimum requirement for investing more work on it :-).

So I gave it a try, added it to NPM and added bluefox as owner of the npm package (https://www.npmjs.com/package/iobroker.mystrom-wifi-switch)

Then I forked ioBroker.repositories and added mystrom-wifi-switch to sources-dist.json. Created a pull request wiuth that change.

Is this ok?

**Comment by GermanBluefox** [comment]
Looks good. Just fix the logo :)

**Comment by rgwch** [comment]
Thank you very much for your feedback and the work in the pull requests!

**Comment by rgwch** [comment]
tried today
