### ISSUE TITLE
File index_m.html not found

### ISSUE THREAD

**Issue by floeny** [rgwch/ioBroker.mystrom-wifi-switch#11]
Hi
after i install the mystrom adapter from github und add an adapter i get following error:
File index_m.html not found
I could'nt set an IP or doing any config. 
OS: win32
Version: 1.2.3

**Comment by rgwch** [comment]
Current version was 0.9.0, so I'm not sure, what you mean with 1.2.3...
Please try the new version 0.10.0. It works on my Raspberry with admin3, can't test on windows.

**Comment by floeny** [comment]
Hi rgwch
it works to on my Raspberry with admin3 (3.3.5) but if i test the windows installation, also with admin3 (3.4.6) i became the above error. The Version that i discribe at the beginning was false sorry. Thanks for your work!

**Comment by rgwch** [comment]
Is the problem solved with the new version 0.10.1?

**Comment by floeny** [comment]
Hi rgwch,
yes the problem is solved with the new version. I have uninstall and install the adapter again. Perfect!

Thank you for your Work!
floeny
