### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by endurance0** [rgwch/ioBroker.mystrom-wifi-switch#23]
Hello

I've installed 2 Instances, but i got no Informations:

![image](https://user-images.githubusercontent.com/64706238/83962839-2f00bd00-a8a1-11ea-86a2-49e5f379456f.png)

reload of Instance:

mystrom-wifi-switch.0 | 2020-06-07 09:29:09.088 | info | (28664) setting interval to 15 seconds
-- | -- | -- | --
mystrom-wifi-switch.0 | 2020-06-07 09:29:09.073 | info | (28664) Fetching http://192.168.1.90/report
mystrom-wifi-switch.0 | 2020-06-07 09:29:08.868 | info | (28664) starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.mystrom-wifi-switch, node: v12.16.3
host.raspberrypi | 2020-06-07 09:29:07.033 | info | instance system.adapter.mystrom-wifi-switch.0 started with pid 28664
host.raspberrypi | 2020-06-07 09:29:05.049 | info | instance system.adapter.mystrom-wifi-switch.0 terminated with code 156 (156)
host.raspberrypi | 2020-06-07 09:29:05.049 | error | Caught by controller[3]: (node:21718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
host.raspberrypi | 2020-06-07 09:29:05.048 | error | Caught by controller[3]: at processTimers (internal/timers.js:492:7)
host.raspberrypi | 2020-06-07 09:29:05.048 | error | Caught by controller[3]: at listOnTimeout (internal/timers.js:549:17)
host.raspberrypi | 2020-06-07 09:29:05.048 | error | Caught by controller[3]: at Timeout.checkStates [as _onTimeout] (/opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build/main.js:124:16)
host.raspberrypi | 2020-06-07 09:29:05.048 | error | Caught by controller[3]: at __awaiter (/opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build/main.js:7:12)
host.raspberrypi | 2020-06-07 09:29:05.048 | error | Caught by controller[3]: at new Promise (<anonymous>)
host.raspberrypi | 2020-06-07 09:29:05.047 | error | Caught by controller[3]: at /opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build/main.js:11:71
host.raspberrypi | 2020-06-07 09:29:05.047 | error | Caught by controller[3]: at Generator.next (<anonymous>)
host.raspberrypi | 2020-06-07 09:29:05.047 | error | Caught by controller[3]: at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build/main.js:125:37)
host.raspberrypi | 2020-06-07 09:29:05.047 | error | Caught by controller[3]: (node:21718) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
host.raspberrypi | 2020-06-07 09:29:05.046 | error | Caught by controller[2]: (node:21718) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by
host.raspberrypi | 2020-06-07 09:29:05.046 | error | Caught by controller[1]: at processTimers (internal/timers.js:492:7)
host.raspberrypi | 2020-06-07 09:29:05.046 | error | Caught by controller[1]: at listOnTimeout (internal/timers.js:549:17)
host.raspberrypi | 2020-06-07 09:29:05.046 | error | Caught by controller[1]: at Timeout.checkStates [as _onTimeout] (/opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build/main.js:124:16)
host.raspberrypi | 2020-06-07 09:29:05.045 | error | Caught by controller[1]: at __awaiter (/opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build/main.js:7:12)
host.raspberrypi | 2020-06-07 09:29:05.045 | error | Caught by controller[1]: at new Promise (<anonymous>)
host.raspberrypi | 2020-06-07 09:29:05.045 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build/main.js:11:71
host.raspberrypi | 2020-06-07 09:29:05.044 | error | Caught by controller[1]: at Generator.next (<anonymous>)
host.raspberrypi | 2020-06-07 09:29:05.044 | error | Caught by controller[1]: at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build/main.js:125:37)
host.raspberrypi | 2020-06-07 09:29:05.043 | error | Caught by controller[1]: (node:21718) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
mystrom-wifi-switch.0 | 2020-06-07 09:29:04.509 | info | (21718) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
mystrom-wifi-switch.0 | 2020-06-07 09:29:04.507 | info | (21718) terminating
mystrom-wifi-switch.0 | 2020-06-07 09:29:04.507 | info | (21718) cleaned everything up...
mystrom-wifi-switch.0 | 2020-06-07 09:29:04.504 | info | (21718) Got terminate signal TERMINATE_YOURSELF
host.raspberrypi | 2020-06-07 09:29:04.498 | info | stopInstance system.adapter.mystrom-wifi-switch.0 send kill signal
host.raspberrypi | 2020-06-07 09:29:04.490 | info | stopInstance system.adapter.mystrom-wifi-switch.0 (force=false, process=true)

**Comment by rgwch** [comment]
Hm, not sure what happens. Could you please see the adapter to "debug" log level and send again the logs? And show me your adapter settings for the switch?

**Comment by rgwch** [comment]
Please try the brand new 2.0.3 version.

**Comment by rgwch** [comment]
No answer since 3 days, so I guess it's ok. Reopen if there's still a problem.
