### ISSUE TITLE
Naming the Instance?

### ISSUE THREAD

**Issue by valbuz** [rgwch/ioBroker.mystrom-wifi-switch#24]
hey
is there a way to renaming the instances?
when having a lot of the switches it's difficult to see which is which :-)

thanks
pat

**Comment by rgwch** [comment]
Sure. Just double-click in the column "Title". See image
![Screenshot from 2020-06-10 12-41-31](https://user-images.githubusercontent.com/3314994/84258846-e7d03180-ab17-11ea-8abc-b70d71e67136.png)

**Comment by valbuz** [comment]
thanks! yes but what about in the objects?
![image](https://user-images.githubusercontent.com/35503440/84259955-8741f400-ab19-11ea-8a8f-d346376fe07d.png)

**Comment by valbuz** [comment]
When i restart the Instance, the description will lost...

**Comment by rgwch** [comment]
I see.. seems to be an ioBroker thing. I don't know how to make such states persistent right now. Must postpone this for now.

**Comment by valbuz** [comment]
OK, i'm waiting...
