### ISSUE TITLE
Steckdosen werden ausgeschalten

### ISSUE THREAD

**Issue by JackDaniel007** [rgwch/ioBroker.mystrom-wifi-switch#26]
Bei einem Adapter start/neustart oder bei einem IoBroker neustart, werden immer die verbundenen Steckdose ausgeschalten :(

**Comment by rgwch** [comment]
Stimmt. Das ist eine definierte "fail safe" Ausgangssitiation, so dass etwa nach einem Stromausfall nicht unkontrolliert alles Mögliche eingeschaltet wird. Aber man könnte das konfigurierbar machen, einverstanden. Werde es mir anschauen.

**Comment by JackDaniel007** [comment]
ja bitte, ist halt zb. bei einem gefrierschrank nicht so toll wenn ein iobroker neustart oder ein kurzer stromausfall in den strom abdreht.
bei meinen zwave steckdosen gibt es folgende optionen  "0": "Switch Off", "1": "Last switch state","2": "Switch On" unter Restore_switch_state_mode

**Comment by rgwch** [comment]
Sehe ich grundsätzlich ein, auch wenn ich den Sinn einer schaltbaren Steckdose beim Gefrierschrank jetzt nicht so unmittelbar erkenne. Aber wie gesagt: Ich schau es mir an, ob ich da eine Option wie "last switch state" einbauen kann.

**Comment by JackDaniel007** [comment]
hehe :)
hier liegt der sinn nicht im "schalten", sondern um zu sehen das er eingeschalten ist, und um den verbrauch aufzuzeichen.
danke im voraus.

**Comment by rgwch** [comment]
Jetzt hab ich's kapiert :-)

Sollte jetzt gehen mit 2.0.6 (https://github.com/rgwch/ioBroker.mystrom-wifi-switch/archive/2.0.6.tar.gz), bitte testen und Issue ggf. schliessen.

**Comment by JackDaniel007** [comment]
Danke es funktioniert nun perfekt.
