### ISSUE TITLE
LOG Einträge / Log entries

### ISSUE THREAD

**Issue by KohlerMike** [rgwch/ioBroker.mystrom-wifi-switch#29]
Besten Dank für den Adapter. Er funktioniert soweit gut. Jedochwird bei jedem Abfrageintervall wird ein Log Eintrag (info) geschrieben.  Das muss doch nicht sein.
Version 2.0.4

Thanks for the adapter. It works well so far. But with each query interval a log entry (info) is written.  That does not have to be.
Version 2.0.4

Quelle | Zeit | debug |  Meldung
-- | -- | -- | --
mystrom-wifi-switch.0 | 2020-10-06 00:08:14.715 | info | (24846) result {"power":0,"Ws":0,"relay":false,"temperature":11.75}
mystrom-wifi-switch.0 | 2020-10-06 00:08:14.607 | info | (24846) Fetching http://192.168.1.220/report
mystrom-wifi-switch.0 | 2020-10-06 00:08:14.606 | info | (24846) checkstates url http://192.168.1.220

**Comment by rgwch** [comment]
Danke für die Rückmeldung!

Das liegt halt am LogLevel: Bei "Info" gehört m.E. ein Eintrag für jede Aktivität ins Log. Aber ich bin einverstanden, dass da eine Zeile statt dieser drei Zeilen genügen würde, werde das ändern. (Hintergrund: Wenn etwas nicht wie erwartet funktioniert, will man ja in der Regel wissen, ob und wie der Adapter mit dem Gerät überhaupt Kontakt hat).
Wenn es zu viele Einträge sind, kann man ja den Log Level auf "warn" setzen, oder die Quelle entsprechend filtern, dass nur noch die interessierenden Einträge auftauchen.

**Comment by JackDaniel007** [comment]
beim unifi adapter kommt bei info auch nur ein "update done", finde auch das ein ausführlicher log eher was für debug wäre

**Comment by rgwch** [comment]
2.0.5 -> log Einträge auf eine Zeile verkürzt. (Ob "update done" oder direkt das Resultat des Updates steht, macht den Braten nicht fett). Bei Debug kommen mehr Meldungen, aber Debug ist je nach Browser auch gar nicht mal so einfach einzuschalten...
