### ISSUE TITLE
Error message and adapter doesn't creat an object

### ISSUE THREAD

**Issue by noaboa97** [rgwch/ioBroker.mystrom-wifi-switch#3]
Hello,

I've installed the adapter. I've set the correct IP of my Switch and set the polling intervall but the adapter says not connected and no sign of life.

![bildschirmfoto 2018-06-09 um 11 49 30](https://user-images.githubusercontent.com/30494947/41190240-34840016-6bdb-11e8-91df-4fab26479c0a.png)

I'm getting this Error message in the logfiles:

startInstance mystrom-wifi-switch.1: cannot find start file!

The object isn't shown unless I activate the expert mode.

**Comment by rgwch** [comment]
Could you please try to update to 0.8.2 (a simple reinstall should do) and tell me, if it works?

**Comment by noaboa97** [comment]
Thanks for your fast reply, I've already got 0.8.2 but I still did a reinstall but I still not working.

**Comment by rgwch** [comment]
Please try Version 0.8.3. It works here, had some missing changes from the Adapter name change. Sorry for that. Please let me know, if ot works now.

**Comment by noaboa97** [comment]
Works for me now. Thanks! Is there a standard polling time and or what should I but there? HOw many seconds are good?

**Comment by rgwch** [comment]
If you want to drive a User Interface, I would recommend about 15 seconds. I use it mainly for fully automated jobs such as loading the car if the solar power is sufficient, and thus I use 300 Seconds. 
The network load for a single REST call is not very high, so setting 10 or 30 Seconds would not do any harm, I think. If you don't set a value, it will be 60 seconds.
