### ISSUE TITLE
Problem mit Firmware Version 3.82.57

### ISSUE THREAD

**Issue by thomasvoni** [rgwch/ioBroker.mystrom-wifi-switch#31]
MyStrom Switch mit Firmware Version 3.82.57 können keine Verbindung mit dem Adapter (2.0.7 und 2.0.8) mehr herstellen. Status bleibt gelb. Fehlermeldung im Log "(56462) Error while fetching /report: 404"

**Comment by rgwch** [comment]
Kann ich jetzt nicht werten. 404 heisst ja "page not found". Was geschieht denn, wenn Sie in einem Browser Folgendes eingeben: `http://<adresse>/report` ?
Falls das eine "vernünftige" Antwort liefert,  müsste ich warten, bis mir jemand einen Switch mit dieser Version schenkt, um das weiter abzuklären...

**Comment by thomasvoni** [comment]
Normales Webinterface funktioniert, http://<ip-adresse>/report bleibt aber leer!?! Es handelt sich um die WiFi Switch v2 Modelle. In den Release Notes der FW 3.82 steht lediglich "Bugfixes"...

**Comment by thomasvoni** [comment]
Superschnelle Antwort vom MyStrom Support:
"Ist gewollt. Info https://api.mystrom.ch/#intro
Bitte downgrade machen - https://mystrom.ch/fr/support/mystrom-firmware-upgrade-tool/"

Downgrade auf Firmware Version 3.82.46 gemacht, nun funktioniert's wieder!

**Comment by rgwch** [comment]
Vielen Dank fürs Nachfragen. Ich habe es aber noch nicht kapiert. Ist das Problem, dass man die passenden Header mitliefern müsste? Das wäre dann ja an sich machbar.

**Comment by thomasvoni** [comment]
So richtig verstehe ich es auch nicht. Gemäss Doku verstehe ich es auch so, dass der passende Header mitgeliefert werden muss. In der Doku steht aber auch, dass diese Funktion deaktiviert werden kann. Das hat bei mir jedoch nicht funktioniert...

**Comment by rgwch** [comment]
Okay, dann schreibe ich in der Doku, dass der Adapter maximal bis Version  3.82.46 funktioniert. Danke noch mal.

**Comment by bergernetch** [comment]
Ich denke ihr sprecht da von [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)?

Man müsste da vor dem request wie z.B. GET einen sogenannten preflight request (HTTP OPTIONS Methode) machen, der kann z.B. so aussehen:
```
OPTIONS /
Host: <mystrom-switch-ip>
Origin: http://<mystrom-switch-ip>
Access-Control-Request-Method: GET
```
Entweder kommt dann ein error, weil nicht erlaubt oder falls zugelassen:
```
Access-Control-Allow-Origin: http://<mystrom-switch-ip>
Access-Control-Allow-Methods: GET
```

Danach kann wie gewohnt ein GET gemacht werden.

**Comment by guggu1** [comment]
ich habe Firmware 4.0.7, und der Adapter läuft problemlos.


![IMG_3FD8138435C1-1](https://user-images.githubusercontent.com/23314447/236690474-e36361db-1856-4de7-8afc-928bf023f86d.jpeg)
