### ISSUE TITLE
Downgrade Firmware

### ISSUE THREAD

**Issue by GreatEMU** [rgwch/ioBroker.mystrom-wifi-switch#33]
"Downgrade auf Firmware Version 3.82.46 gemacht, nun funktioniert's wieder!"

_Originally posted by @thomasvoni in https://github.com/rgwch/ioBroker.mystrom-wifi-switch/issues/31#issuecomment-734455845_

Wo bekomme ich denn die ältere Firmware?
Auf der Supportseite von MyStrom finde ich mur eine Firmware zur Version 1 des Switch.

**Comment by thomasvoni** [comment]
Ich habe mit dem im Post #31 beschriebenen "Upgrade-Tool" gemacht. Hier nochmals der Link dazu
https://mystrom.ch/de/support/mystrom-firmware-upgrade-tool/

**Comment by rgwch** [comment]
Oder jemand behebt das Problem. Ich werde jeden vernünftig aussehenden pull request gerne mergen. Selber kann ich es nicht machen, weil ich keine Stecker mit der neuen Firmware habe und es darum nicht testen könnte.

**Comment by GreatEMU** [comment]
Das Tool habe ich bereits. Aber ich habe nicht die ältere Firmware für den Downgrade

**Comment by thomasvoni** [comment]
Bei mir hat das Tool automatisch die ältere FW heruntergeladen und installiert. Habe aber gesehen, dass es mir nun auch die Neuere vorschlägt... Ev. bei MyStrom Support anfragen? Oder besser noch, jemand fixt das Problem mit dem Adapter - man möchte ja doch eigentlich die neuste FW drauf haben... :-) 
Leider fehlen mir die Kenntnisse dazu - testen könnte ich es aber schon.

**Comment by GreatEMU** [comment]
Ich bin zwar ein Anwendungsentwickler mit jahrzehntelanger Erfahrung, aber bei ioBroker und GitHub bin ich neu.
Den Switch könnte ich nach Weihnachten leihweise zu Verfügung stellen ;-)

**Comment by Kusi-Schweiz** [comment]
Wurde dem Hersteller ein Switch zur Verfügung gestellt? Ansonsten, könnte auch ich dies testen, wenn mir erklärt wird wie ich genau vorgehen soll.

**Comment by rgwch** [comment]
Ich denke, jemand mit Javascript-Kenntnissen müsste ein neues Modell des Schalters kaufen, um das zu fixen. Ich selber habe nur drei vom alten Modell und brauche keine mehr, werde deshalb derzeit auch keinen kaufen.

**Comment by Kusi-Schweiz** [comment]
Ich habe soeben das Firmwareupdate in der myStrom-App (Android) installiert und bei mir läuft der myStrom Wifi Switch mit dem Adapter noch immer einwandfrei. Einziger Unterschied was mir auffällt, dass die Nachkomma-Stellen von Temperatur und Leistung kürzer sind, was mir persönlich besser gefällt. Beide haben Datenpunkte haben nur noch 2 Nachkomma-Stellen.

**Comment by GreatEMU** [comment]
Ich habe es gerade dann auch noch mal getestet, aber bekomme immer noch den gleichen Fehler im Adapter gemeldet:
`(16379) Fatal error during fetch FetchError: request to http://192.168.178.060/report failed, reason: connect EHOSTUNREACH 192.168.178.48:80`

Meine Versions-Stände:
MyStrom-Switch: 3.82
MyStrom-Adapter 8ioBroker): 2.0.8

**Comment by rgwch** [comment]
Dazu habe ich mich aber schon mal geäussert: Man darf die IP-Adresse nicht "pseudo-oktal" eintragen. (Also  nicht 192.168.178.060, sondern 192.168.178.60). 060 wird als 48 interpretiert und dort ist wohl wirklich kein Mystrom Switch zu finden.

**Comment by Kusi-Schweiz** [comment]
Ich habe übrigens jetzt die Firmware-Version 3.82.60 installiert, mit welcher der Adapter funktioniert.

**Comment by GreatEMU** [comment]
Was so eine kleine 0 bewirken kann...
Den Hinweis auf "pseudo-oktal" hatte ich wohl überlesen.
Jetzt wird die Verbindung hergestellt.

**Comment by Tobias8610** [comment]
Wo finde ich die Firmware Version MyStrom-Switch: 3.82
