### ISSUE TITLE
startInstance mystrom-wifi-switch.0: cannot find start file!

### ISSUE THREAD

**Issue by fenderlein** [rgwch/ioBroker.mystrom-wifi-switch#35]
Ich bekomme bei allen Instanzen jetzt folgende Fehlermeldung im IOBroker:

startInstance mystrom-wifi-switch.3: cannot find start file!

Node.js v12.20.0
NPM 6.14.8
ioBroker 3.1.6

**Comment by rgwch** [comment]
Wie ist "jetzt" zu verstehen? Nach einem Update des Adapters? Auf welche Adapterversion? Die Fehlermeldung deutet darauf hin, dass die Kompilate fehlen, also das Verzeichnis "build" resp. dessen Inhalt.

**Comment by fenderlein** [comment]
Ich habe die Version 2.0.8 installiert. 
Irgendwann in der letzten Nacht muss das Problem aufgetreten sein. Wann genau kann ich nicht sagen.
Gestern hab ich auf dem Raspi lediglich ein sudo apt-get update und upgrade durchgeführt. 
Ein iobroker rebuild mystrom-wifi-switch habe ich auch versucht, allerdings ohne Erfolg.

**Comment by rgwch** [comment]
Vorschlag:
- ioBroker Log löschen
- Adapter nochmal frisch von https://github.com/rgwch/ioBroker.mystrom-wifi-switch/archive/2.0.8.tar.gz installieren
- ioBroker Log anschauen

Steht im  Log dann etwas Spannendes?

Wenn nein: 

     ssh raspi
     cd /opt/iobroker/node_modules/iobroker.mystrom-wifi-switch/build
     ls

Wie siehts da drin aus?

**Comment by GreatEMU** [comment]
Hallo

Ich habe die Version 2.0.8. frisch installiert.
Hier der Auszug aus dem Log:

```
2020-12-17 11:30:44.286 - info: mystrom-wifi-switch.0 (24862) starting. Version 2.0.8 in /opt/iobroker/node_modules/iobroker.mystrom-wifi-switch, node: v12.20.0, js-controller: 3.1.6
--
2020-12-17 11:30:44.545 - error: mystrom-wifi-switch.0 (24862) Fatal error during fetch TypeError: Only absolute URLs are supported
2020-12-17 11:30:44.547 - info: mystrom-wifi-switch.0 (24862) result from :undefined

```

Im build-Verzeichnis befindet sich nur eine main.js

Nur zum Verständnis: Soll die Version das Problem mit der neuesten Firmware beheben oder muss benötige ich immer noch den downgrade?

**Comment by rgwch** [comment]
Die Fehlermeldung deutet auf eine nicht interpretierte IP-Adresse in den Einstellungen hin. Es sollte dort etwas wie http://192.168.0.45 stehen (nicht nur 192.168.0.45).

Nein, das Problem mit dem  Firmware upgrade ist damit nicht behoben. Da ich keinen aktuellen MyStrom Switch besitze, kann ich mich derzeit auch nicht damit befassen.

**Comment by GreatEMU** [comment]
Die komplette Fehlermeldung lautet
(26575) Fatal error during fetch FetchError: request to http://192.168.178.060/report failed, reason: connect EHOSTUNREACH 192.168.178.48:80
Wobei ich bei mir kein Gerät mit der IP *48 habe. 
Aber ich habe auch die aktuellste Firmware.

Wie in einem anderen Post erwähnt, könnte ich dir 1 Switch leihweise zu Verfügung stellen. (Wenn die Weihnachtsbeleuchtung abgebaut wurde ;-) )

**Comment by rgwch** [comment]
060 wird oktal interpretiert, also 6*8=48.  EHOSTUNREACH heisst, es wurde nichts bei 192.168.178.48 gefunden....
Wenn du 48 haben willst, musst du 192.168.178.48 schreiben :-) Zugegeben, das ist ein wenig unintuitiv, stammt aber nicht von mir, sondern vom darunterliegenden JavaScript. 0x60 ist hexadezimal 60, also 96, 060 ist oktal 60, also 48. Nur 60 ist 60.

Andere Hardwarehersteller offerieren OpenSource Programmierern meistens ein Exemplar ihres Geräts. Insbesondere wenn es für die betreffende Plattform nicht viele Alternativen an Software gibt. Immerhin bekommen sie auf diese Weise etwas gratis, für das sie sonst ein bis zwei Tausender springen lassen müssten. Okay, das mit der Leihgabe können wir vlt. im Hinterkopf behalten, aber jetzt gerade bin ich Corona hin oder her schon anderweitig recht ausgelastet.

**Comment by fenderlein** [comment]
zur Info. Mein Problem wurde durch die Neuinstallation gelöst. Geht jetzt wieder. Danke für den Tipp!
