### ISSUE TITLE
Please add support of Admin3

### ISSUE THREAD

**Issue by GermanBluefox** [rgwch/ioBroker.mystrom-wifi-switch#6]
For all new adapters it is required the support of admin3.
You can just copy it from somewhere.
and add "materialize": true to io-package.json/common

**Comment by rgwch** [comment]
Sorry, I don't get this.Google seems not to like me today, and even here https://github.com/ioBroker/ioBroker/wiki/Adapter-Development-Documentation i am not able to find anything about Admin3. Can you give me a hint?

**Comment by rgwch** [comment]
Well, I installed it in an admin3-Environment, and it works with admin3.

**Comment by GermanBluefox** [comment]
Please make a index_m.html file, like in here: 
https://github.com/ioBroker/ioBroker.template/blob/master/admin/index_m.html
and set this flag:
https://github.com/ioBroker/ioBroker.template/blob/master/io-package.json#L70

**Comment by rgwch** [comment]
[X] done. 
But.. I don't see any difference in my mac/raspberry environment :-)
